import React, {Component} from 'react';

import TreeItem from './TreeItem/TreeItem';

const data = {
    name: 'root',
    toggled: false,
    cursor: false,
    children: [
        {
            name: 'SERVERS'
        },
        {
            name: 'SECURITY DEFINITIONS',
            children: [
                { name: 'User security' },
                { name: 'Admin security' }
            ]
        },
        {
            name: 'TESTS',
            children: [
                {
                    name: 'autogenerated'
                },
                {
                    name: 'Semi-automated',
                    children: [
                        {
                            name: 'Suite 1',
                            children: [
                                {
                                    name: 'manual test 1'
                                },
                                {
                                    name: 'veeeeeeeeeeeeeeeeeeerrrrrrrrryyyyyyyy long manual test 2'
                                }
                            ]
                        },
                        {
                            name: 'Suite 2',
                            children: [
                                {
                                    name: 'manual test 1',
                                    children: 5
                                },
                                {
                                    name: 'manual test 2'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            name: 'TEST RUNS',
            children: [
                {
                    name: 'autogeneration 7.05.2018'
                },
                {
                    name: 'Manual 9.05.2018'
                }
            ]
        }
    ]
};

export const buildTree = (object) => {
    if('children' in object && object['children'] instanceof Array) {
        const elems = object['children'].map((elem, index) => {
            let component = (
                <TreeItem elem={elem} nested={buildTree(elem)} key={index} />
            );
            return component;
        });
        return (
            <ul>
                {elems}
            </ul>
        );
    } else {
        return null;
    }

};

class TreeObject extends Component {

    render() {
        return (
            <div>
                <h1>{data.name}</h1>
                {buildTree(data)}
            </div>
        );
    }
}

export default TreeObject;